### ISSUE TITLE
Jupyter notebook requires flash attention import and A100 GPU or newer

### ISSUE THREAD

**Issue by delalamo** [TattaBio/gLM2#1]
The jupyter notebook in this repo, categorical_jacobian_gLM2.ipynb, requires the flash attention package to be installed. This can be done with a simple modification that adds the following two lines to the first cell:
```
!pip install flash-attn --no-build-isolation
import flash_attn
```
Additionally, flash attention requires an A100 or newer GPU; T4 GPUs are not supported. It might be worth adding that to the notebook as well
Thanks!
Diego

**Comment by scopello** [comment]
Hi @delalamo,

I have updated the model implementation to use `torch.nn.functional.scaled_dot_product_attention` instead of requiring flash attention. See https://github.com/TattaBio/gLM2/pull/2. 

-Andre
