### ISSUE TITLE
how are contigs sampled for training?

### ISSUE THREAD

**Issue by wconnell** [TattaBio/gLM2#5]
> UPDATE(09/2024): We updated the model with longer context length (4096 tokens vs. 2048 tokens) and per-nucleotide IGS tokenization.

Appendix C panel D shows the avg contig length is easily larger than the training context window.
<img width="413" alt="Screen Shot 2024-10-04 at 11 23 35 AM" src="https://github.com/user-attachments/assets/9ad8b1a9-5040-417f-b202-2c12af283f8b">

Can you clarify how training samples are created? Thanks!

**Comment by scopello** [comment]
Hi @wconnell, for each contig, we tokenize the sequence, then chunk by 4096 tokens to generate training examples
